swagger: "2.0"
info:
  description: "This documentation will support integrations with Pokedex."
  version: "1.0.0"
  title: "API Pokedex"
tags:
- name: "pokemons"
  description: "Collection pokemons"
schemes:
- "http"
- "https"
paths:
  /api/pokemon:
    get:
      tags:
        - "pokemons"
      summary: "Get list of pokemons"
      produces:
      - "application/json"
      parameters:
      - name: "page"
        in: "query"
        description: "number page"
        required: true
        type: "integer"
        format: "int64"
      - name: "limit"
        in: "query"
        description: "Top list"
        required: true
        type: "integer"
        format: "int64"
      - name: "text"
        in: "query"
        description: "Word for search"
        type: "string"
      responses:
        "200":
          description: "OK"
